################################################################################
# \file bsp.mk
#
# \brief
# Define the CYW943907AEVAL1F target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=WIFI_INTERFACE_M2M CYW943907AEVAL1F

# Any additional defines to apply when using this board.
BSP_DEFINES:=CY_USING_HAL

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYW43907KWBG
DEVICE:=CYW43907KWBG
DEVICE_COMPONENTS:=4390X CAT4
DEVICE_CYW43907KWBG_DIE:=4390x
DEVICE_CYW43907KWBG_FLASH_KB:=0
DEVICE_CYW43907KWBG_SRAM_KB:=2048
DEVICE_LIST:=CYW43907KWBG
DEVICE_TOOL_IDS:=bsp-assistant library-manager project-creator
RECIPE_DIR:=$(SEARCH_recipe-make-cat4)
